### ISSUE TITLE
Install issue on Windows using Bash

### ISSUE THREAD

**Issue by MahaDEEB** [sekika/swrcfit#10]
Hi,

I followed the instructions for installing on Windows using Bash, but the `make install` command fails.

![image](https://user-images.githubusercontent.com/33014670/46123253-5f96e500-c1eb-11e8-9f47-19c737ab25ab.png)

I confirm I installed `octave-optim` and that I can run octave directly. 

Any clue on how to pass this? 

Thank you,

**Comment by sekika** [comment]
Hi, Thanks for the report.

I released version 3.1 now. Please test with the new version.

Recently behaviour of Octave is changing with versions and it may still have some problem regarding the octave-forge package. But anyway I confirmed that the new version works on Windows right now.

**Comment by MahaDEEB** [comment]
Hi @sekika I tried the new version 3.1 and it works flawlessly now on Windows 10 through Bash. Thank you so much for fixing the issue quickly!
