### ISSUE TITLE
what soil classification system used in SWRC Fit

### ISSUE THREAD

**Issue by jiangyangliu** [sekika/swrcfit#11]
Hello

Because in SWRC fit I need to add soil texture type. I have a question that what soil texture classification system is used, usda, WRB or others. Maybe it is shown somewhere but I am sorry for not finding that.

Thank you

**Comment by sekika** [comment]
The sample data of SWRC Fit are from UNSODA database, as written in the page of SWRC Fit. UNSODA database uses USDA classification system. SWRC Fit does not use the information of soil texture for determining the model parameters. If you make your own analysis of your SWRC data, you can use any classification system that you like and describe it in your result.

**Comment by jiangyangliu** [comment]
Thanks a lot. I get it. It is very clear and convenient.
