### ISSUE TITLE
Install on Cygwin / Correction function of FX model

### ISSUE THREAD

**Issue by Afiverz** [sekika/swrcfit#12]
Dear @Sekika San, thank you very much for your program, really helpful, but I have some questions.

1. I have a hard time installing this swrc, on my laptop (windows 8.1) using cygwin. Is it possible to install it?

2. I already tried using cygwin, but seems like it has a problem related to octave. Can you explain me a how to install it properly? since I have limited knowledge about cygwin. 

2. Today, march 9, 2019. I can not access swrc web interface, it said errors when I open it.

Domo arigatou gozaimasu

**Comment by sekika** [comment]
Dear @Afiverz, thank you for your feedback.

1 and 2: It was possible to install SWRC fit with cygwin several years ago when I installed it and wrote the description. Recently I do not use cygwin and there may be some problem now. Actually I do not have Windows PC now in my home. I may check cygwin maybe several weeks later when I have access to Windows 10 PC and if I find something I will rewrite the installation instruction and post it here.

3. PURL link from
http://purl.org/net/swrc/
to
http://seki.webmasters.gr.jp/swrc/
is not properly working now. I am not sure if it is a temporal problem. Please go to the web interface from
http://seki.webmasters.gr.jp/swrc/
If the problem persist, I will rewrite the link.

**Comment by Afiverz** [comment]
Dear @sekika san,

Thankyou very much for your quick response and explanation. Now I can access to new link you've given to me. I am really appreciate your help on your program. 
Thank you very much

**Comment by Afiverz** [comment]
Dear @sekika san,

I have one more question, I found most on paper related to SWCC by using Fredlund & Xing (1994). They used equation like first 2 picture below. While on your program I saw you use like third picture (from your web interface). 

My question, do you use same approachment as first 2 pictures equation and equation on your web interface on your fitting curve? If yes, can you explain? I found quite hard to  understand because my limitation knowledge. 
Thankyou very much again.

![SWCC](https://user-images.githubusercontent.com/48321763/54082495-061a1100-435a-11e9-8af8-ac01502fe920.PNG)
![swrc](https://user-images.githubusercontent.com/48321763/54082498-10d4a600-435a-11e9-981a-2f5b18842ce9.PNG)
![sww](https://user-images.githubusercontent.com/48321763/54082501-15995a00-435a-11e9-95a4-77baa9968382.PNG)

**Comment by sekika** [comment]
They are the same equations except correction function and theta_r. Please click "show more options" and you can set theta_r = 0 constant and correction function. See figures below.
![Fig1](https://raw.githubusercontent.com/wiki/sekika/swrcfit/options-fx.png)
![Fig2](https://raw.githubusercontent.com/wiki/sekika/swrcfit/fx-correction.png)

**Comment by Afiverz** [comment]
Oh I see, now I understand. I currently learn about this topic and your application really helpful. 説明してくれて、本当にありがとうございます、先生。

**Comment by sekika** [comment]
PURL link recovered.
