### ISSUE TITLE
error: package struct is not installed

### ISSUE THREAD

**Issue by 376013550** [sekika/swrcfit#13]
swrcfit swrc.txt
error: package struct is not installed
error: called from
    load_packages at line 41 column 7
    pkg at line 457 column 7
    /usr/local/bin/swrcfit at line 11 column 1

Mac

**Comment by sekika** [comment]
Please install struct and other packages by running following command from terminal and see if it works.

octave -q --eval "pkg install -forge struct optim nan"

**Comment by 376013550** [comment]
The following error:
error: the following dependencies were unsatisfied:
   optim needs statistics >= 1.4.0
