### ISSUE TITLE
Calculating Sand Silt Clay from measured data

### ISSUE THREAD

**Issue by TylerGriffin99** [sekika/swrcfit#14]
Is it possible to take the measured data and return both VG params and sand silt clay percentages?

If not possible in SWRC can this be performed in Rossetta which i assume SWRC is based on?

**Comment by sekika** [comment]
No. In Rosetta VG parameters can be estimated from some parameters such as bulk density and sand silt clay percentages and can be used for initial estimate of fitting VG parameters. SWRC fit does not need any initial estimate of parameters and therefore it is different from Rosetta. Rosetta does not estimate sand silt clay percentage from SWRC data.

**Comment by TylerGriffin99** [comment]
> No. In Rosetta VG parameters can be estimated from some parameters such as bulk density and sand silt clay percentages and can be used for initial estimate of fitting VG parameters. SWRC fit does not need any initial estimate of parameters and therefore it is different from Rosetta. Rosetta does not estimate sand silt clay percentage from SWRC data.

Are you aware of a way to take measured data (VMC and kPa) and estimate sand silt clay percentages by chance?

**Comment by TylerGriffin99** [comment]
or estimate sand silt clay from the VG parameters the are generated by SWRC?

**Comment by sekika** [comment]
No. I do not know such work.
