### ISSUE TITLE
水分特性曲線の入力するデータについて

### ISSUE THREAD

**Issue by sachkoko** [sekika/swrcfit#16]
水分特性曲線の入力する土質データにおいて，体積含水率ではなく飽和度を入力し，フィッティングを行うにはどうしたらいいでしょうか．

**Comment by sekika** [comment]
似たような質問はこちらにもありましたが、体積含水率に変換すればいいだけです。

https://github.com/sekika/swrcfit/issues/15

飽和度 Sr = Vw/Vv
体積含水率 θ = Vw / V
間隙比 e = Vv / Vs

より、間隙比が分かれば  θ = (e/(1+e)) Sr と換算できます。

つまり、間隙比が一定であれば Sr と θ は比例関係にあるので、SWRCモデルはすべてこのプログラムでそのままフィッティングできます。θrとθsをそれぞれ対応する Sr に変えれば、Seは等しくなるので他のパラメータは等しくなります。

**Comment by sachkoko** [comment]
ありがとうございます
