### ISSUE TITLE
Uncertainties for model parameters

### ISSUE THREAD

**Issue by Helpme47** [sekika/swrcfit#17]
Hello Katsutoshi Seki,
is it possible for SWRC fit to produce uncertainties for the model parameters similar to the r package Hydrome?

**Comment by sekika** [comment]
When parameter adv=1 is set, correlation matrix and standard deviation are shown. See this page.

https://github.com/sekika/swrcfit/blob/master/doc/en/setting.md

**Comment by Helpme47** [comment]
I'm assuming this is in the offline version? I have spent a large amount of time trying to download SWRC fit using Bash and cygwin instructions from https://github.com/sekika/swrcfit/blob/master/doc/en/install-windows.md but with no success. Is there another way of downloading?

**Comment by sekika** [comment]
I don't have Windows machine to test right at the moment. I haven't tested on Windows for a while and the environment has changed. It looks like forge packages are now installed properly, and the instruction written in the mac page https://github.com/sekika/swrcfit/blob/master/doc/en/install-mac.md could be tested. So could you try running

octave -q --eval "pkg install -forge struct optim nan"

in cygwin terminal?

**Comment by Helpme47** [comment]
Unfortunately i get this error:
$ octave -q --eval "pkg install -forge struct optim nan"
error: the following dependencies were unsatisfied:
   optim needs statistics >= 1.4.0

What device do you use that works? Mac or Linux?

**Comment by sekika** [comment]
That error comes when you don't have the data file, swrc.txt. Make sure that you have your data file in the same directory where you are running the code, or specify the file with full path.

**Comment by Helpme47** [comment]
[SWRCFit.xlsx](https://github.com/sekika/swrcfit/files/5639751/SWRCFit.xlsx)
I can't seem to get it working. 
I have attached the data that i want fitted (only a few data points), would it be possible for you to optimize the kosugi and Brooks and Corey equations and send the results back to me with the standard deviation of the model parameters and other uncertainty statistics if available. I realize I am asking a bit, but i would really appreciate the help.

**Comment by sekika** [comment]
Here is the result. Statistics data for BC model was not obtained. I am not sure why. One possible reason is that the curve does not have air entry value. I am also showing VC model.

=== Input data ===

3	0.132364
10	0.06585
20	0.057224
40	0.050385
60	0.044425
80	0.04565
160	0.033088375
260	0.031811195
330	0.030720362
370	0.030326968
670	0.028805137
740	0.028654775
750	0.026744456
870	0.027769505
1540	0.024070011
1570	0.021437128
1570	0.022906738
1670	0.023337476
1740	0.023218159

=== BC model ===
qs = 0.1503
qr = 0.022454
hb = 2.1883
lambda = 0.5724
R2 = 0.9811
CorrelationMatrix =

    NA    NA    NA    NA
    NA    NA    NA    NA
    NA    NA    NA    NA
    NA    NA    NA    NA

StandardDeviation =

    NA
    NA
    NA
    NA

=== VG model ===
qs = 0.1486
qr = 0.020375
alpha = 0.3333
n = 1.5511
R2 = 0.9549
CorrelationMatrix =

   1.0000  -0.6610  -0.9709  -0.8177
  -0.6610   1.0000   0.7488   0.9152
  -0.9709   0.7488   1.0000   0.9114
  -0.8177   0.9152   0.9114   1.0000

StandardDeviation =

   3.5784e-02
   5.0980e-03
   3.1561e+00
   1.7833e-01

=== LN model ===
qs = 0.2168
qr = 0.025129
hm = 3.0000
sigma = 2.2711
R2 = 0.9544
CorrelationMatrix =

   1.0000  -0.6374   0.9976   0.9740
  -0.6374   1.0000  -0.6383  -0.7292
   0.9976  -0.6383   1.0000   0.9812
   0.9740  -0.7292   0.9812   1.0000

StandardDeviation =

   1.5870e-01
   2.9038e-03
   6.7762e+00
   1.0905e+00

**Comment by Helpme47** [comment]
Brilliant, thank you very much! The last detail is i am trying to get the uncertainty for water content values at particular points on the van Genuchten curve (namely -4.8 kPa and -1500 kPa) for the data above. Would you be able to calculate this/know how i may be able to calculate this? I understand if I am asking too much, but any help would be greatly appreciated.

B

**Comment by sekika** [comment]
Model parameters have uncertainties because they do not fit actual data perfectly. The actual data also have uncertainty which come from experimental procedure, but they are not related to fitting, because they should be determined before fitting. You can calculate standard deviation for each point if it has multiple points, but calculating SD for a single point in impossible.

**Comment by Helpme47** [comment]
Thank you for all your help!
