### ISSUE TITLE
計算結果が表示されない

### ISSUE THREAD

**Issue by nicekazu** [sekika/swrcfit#3]
2.0をインストールして、swrcfitのチェックをすると以下のようになります。
恐れ入りますが、原因が分かりましたら助かります。

Owner@Owner-msi /usr/bin
$ swrcfit swrc.txt
octave: X11 DISPLAY environment variable not set
octave: disabling GUI teatures
=== BC model ===

Owner@Owner-msi /usr/bin

**Comment by sekika** [comment]
まず「octave: X11 DISPLAY environment variable not set」のメッセージは、
グラフを表示するための X の設定ができていないということなので、
インストール方法に書いたように、Windows であれば Cygwin/X の実行が
必要です。他の環境でも、設定が必要になります。
グラフを表示しないのであれば、そこは無視しても大丈夫です。

=== BC model === 
の後に、計算結果が表示されない、ということでしょうか。
もしかすると、それはこれからリリースしようとしているバージョン 2.1 に
すると、直るかもしれません。しばらくお待ちください。

**Comment by sekika** [comment]
続き
https://github.com/sekika/swrcfit/issues/4
