### ISSUE TITLE
計算結果が表示されない (2)

### ISSUE THREAD

**Issue by nicekazu** [sekika/swrcfit#4]
早速のご返信ありがとうございます。
計算結果が全く得られないことが一番の問題となっています。
この１ヶ月、ウェブ版は問題はありませんが、他はいろいろ挑戦してもいずれもエラーで終わっております。
なお、swrcfitのインストール（wget http://seki.webmasters.gr.jp/swrc/install.txt; sh install.txt）をやった後から、
octave: X11 DISPLAY engironment variable not set
octave: disabling GUI teatures
のメッセージが出て来ています。
octaveもcygwinも全くの初心者のためよろしくお願いいたします。

**Comment by sekika** [comment]
そのメッセージは、グラフを表示する必要がなければ無視して大丈夫です。
こちらに、追記しておきました。

https://github.com/sekika/swrcfit/wiki/SWRC-Fit-%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB

バージョン 2.1 をリリースしたので、インストールできるかどうか、
wget http://seki.webmasters.gr.jp/swrc/install.txt; sh install.txt
を試してください。

**Comment by sekika** [comment]
この話題に関する返信は、新しいスレッドではなく、このスレッドへのコメントでお願いします。

**Comment by nicekazu** [comment]
ありがとうございました。
計算結果が問題なくでました。
本当に助かりました。
