### ISSUE TITLE
'leasqr' undefined

### ISSUE THREAD

**Issue by lkoppens** [sekika/swrcfit#6]
When trying to run SWRC fit (for any swrc.txt) the program does not run properly and returns:
warning: 'leasqr' undefined near line 159 column 45
warning: called from
    /usr/local/bin/swrcfit at line 165 column 34

I have tried to reinstall homebrew and swrc multiple times, to no avail. 
My machine is running:
OSX 10.11.4
SWRC Fit: 2.1
brew: 0.9.9
(Xcode commandline tools are installed)

**Comment by sekika** [comment]
Thank you for your report. I haven't tried installation in new environment for a while, and something might be wrong now. I am not sure what the problem is, but I am now sending a pull request to change the installation method for homebrew.

https://github.com/Homebrew/homebrew-science/pull/3609/commits/58729002da9e8358b01ce568649834de3ee122d0

After they accept the pull request, you could check if it works. Please wait for several days.

**Comment by sekika** [comment]
@lkoppens
Finally the change to the homebrew formula was accepted.
Please check if it works by trying
brew uninstall swrcfit; brew install swrcfit

**Comment by lkoppens** [comment]
@sekika thanks for the reminder! I have updated brew and then followed your instructions for uninstalling and installing, however, the problem still persists.

After two succesful uninstalls and installs, I got this while trying to install a third time:
==> Installing swrcfit from homebrew/science
Error: You must `brew link ghostscript` before homebrew/science/swrcfit can be installed

After linking ghostscript and retrying, the install worked again, but the original problem was not solved, unfortunately. 

Thanks for your time, luckily I can still work with the web version :)

**Comment by sekika** [comment]
@lkoppens please try installing manually this way.

(1) Uninstall the brew version
    brew uninstall swrcfit
(2) Download the latest version of swrcfit
    wget https://github.com/sekika/swrcfit/archive/v2.1.tar.gz
(3) Unpack the archive and install it
    tar xfvz v2.1.tar.gz
    cd swrcfit-2.1
    ./configure
    make install

Please show me the output at the last stage (make install). If successful, it will be something like

=== Installing manual to /usr/local/share/man/man1
=== Installing /usr/local/bin/swrcfit
=== Cheking swrcfit
/usr/local/bin/swrcfit was installed successfully.

**Comment by lkoppens** [comment]
Thank you, this worked for me!

However, there was more to the output then you described so I've pasted it below because it might be of use for you:
`
=== Installing manual to /usr/local/share/man/man1
=== Installing /usr/local/bin/swrcfit
=== Cheking swrcfit
warning: 'leasqr' undefined near line 159 column 45
warning: called from
    /usr/local/bin/swrcfit at line 165 column 34
Result of swcfit swrc.txt is different from result.txt.
Not yet installed properly. Trying to install Octave forge packages.
=== Installing packages (pkg install -forge struct optim)
warning: creating installation directory /Users/ThomasKoppens/octave
warning: called from
    install at line 30 column 5
    pkg at line 405 column 9
clang: warning: -lsuitesparseconfig: 'linker' input unused
clang: warning: -lmetis: 'linker' input unused
clang: warning: argument unused during compilation: '-L/usr/local/opt/suite-sparse/lib'
clang: warning: argument unused during compilation: '-L/usr/local/opt/metis/lib'
clang: warning: -lsuitesparseconfig: 'linker' input unused
clang: warning: -lmetis: 'linker' input unused
clang: warning: -lsuitesparseconfig: 'linker' input unused
clang: warning: -lmetis: 'linker' input unused
clang: warning: argument unused during compilation: '-L/usr/local/opt/suite-sparse/lib'
clang: warning: argument unused during compilation: '-L/usr/local/opt/metis/lib'
clang: warning: -lsuitesparseconfig: 'linker' input unused
clang: warning: -lmetis: 'linker' input unused
clang: warning: argument unused during compilation: '-L/usr/local/opt/suite-sparse/lib'
clang: warning: argument unused during compilation: '-L/usr/local/opt/metis/lib'
clang: warning: argument unused during compilation: '-L/usr/local/opt/suite-sparse/lib'
clang: warning: argument unused during compilation: '-L/usr/local/opt/metis/lib'
clang: warning: -lsuitesparseconfig: 'linker' input unused
clang: warning: -lmetis: 'linker' input unused
clang: warning: argument unused during compilation: '-L/usr/local/opt/suite-sparse/lib'
clang: warning: argument unused during compilation: '-L/usr/local/opt/metis/lib'
clang: warning: -lsuitesparseconfig: 'linker' input unused
clang: warning: -lmetis: 'linker' input unused
clang: warning: argument unused during compilation: '-L/usr/local/opt/suite-sparse/lib'
clang: warning: argument unused during compilation: '-L/usr/local/opt/metis/lib'
samin.cc:536:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
1 warning generated.
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
clang: warning: -lsuitesparseconfig: 'linker' input unused
clang: warning: -lmetis: 'linker' input unused
clang: warning: argument unused during compilation: '-L/usr/local/opt/suite-sparse/lib'
clang: warning: argument unused during compilation: '-L/usr/local/opt/metis/lib'
clangclang: clang: clang: warning: warning: : warningwarning: : -lsuitesparseconfig: 'linker' input unused-lsuitesparseconfig: 'linker' input unused-lsuitesparseconfig: 'linker' input unused-lsuitesparseconfig: 'linker' input unused



clangclang: : clangwarningwarningclang: : : -lmetis: 'linker' input unused-lmetis: 'linker' input unusedwarning: : 

-lmetis: 'linker' input unusedwarning
: -lmetis: 'linker' input unused
clang: warningclang: clangargument unused during compilation: '-L/usr/local/opt/suite-sparse/lib': : warning
: warningargument unused during compilation: '-L/usr/local/opt/suite-sparse/lib': clangargument unused during compilation: '-L/usr/local/opt/suite-sparse/lib'
: 
warningclang: : clangargument unused during compilation: '-L/usr/local/opt/metis/lib'warning: 
: warningargument unused during compilation: '-L/usr/local/opt/metis/lib': 
argument unused during compilation: '-L/usr/local/opt/metis/lib'
clang: warning: argument unused during compilation: '-L/usr/local/opt/suite-sparse/lib'
clang: warning: argument unused during compilation: '-L/usr/local/opt/metis/lib'
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
For information about changes from previous versions of the struct package, run 'news struct'.
/usr/local/bin/swrcfit was installed successfully.
`

**Comment by sekika** [comment]
Thank you. Now I see that installation script is still working but it doesn't work on the latest Homebrew environment. If I can find the reason, I will fix it.

**Comment by sekika** [comment]
As a temporal solution, I added the following message in the installation instruction for Mac OS X.

When running swrcfit, if you get error message as `warning: 'leasqr' undefined near line ... column ...`, please run the following command from Terminal.

```
octave -q --eval "pkg install -forge struct optim"
```
