### ISSUE TITLE
Soil Water Retention Curve measured with HYPROP (not directly associated with SWRC Fit)

### ISSUE THREAD

**Issue by KamilaF** [sekika/swrcfit#8]
Hello,

I have created graphs from data measured by Hyprop and I found strange thing in each of the graphs - there is strange abnormality, which seems like a "teeth" and it is all the time around pF 1 (10 - 20cm of pressure head) and it is the same for both tensometers, do some of you specialists have an answer to it? I have no idea why it is like this and I need a description of this abnormality.

Thank you.

**Comment by sekika** [comment]
I don't understand your problem. Could you give an example data for verification? If you can't publish your original data here, just change some numbers a little bit and make it a sample data.

**Comment by KamilaF** [comment]
[graph for the question.xlsx](https://github.com/sekika/swrcfit/files/792545/graph.for.the.question.xlsx)

Thank you for your response. Here is one of my graphs with a bit changed data and on the graph you can see what I meant. This abnormality appears on almost every graphs but they were measured at the different time so I do not understand that.

**Comment by sekika** [comment]
Now I understand your problem, but I have no idea why it happens. Water content is gradually decreasing while the tension increases, but the tension decreases remarkably in 30 minutes after 12/15 4:28 (red cell). I don't come up with a possible cause by just looking at this data. There may be some change in the state of equilibrium at the contact to soil, but the change is too abrupt and wierd. As you experience this problem repeatedly, you could contact Decagon Devices to ask for possible causes. I would also like to know the cause if you will get to know it.
