### ISSUE TITLE
Export of results

### ISSUE THREAD

**Issue by TylerGriffin99** [sekika/swrcfit#9]
Is there a way to export the results of the curve? i.e. a csv file with a value every 0.5 KPA and the corresponding % water content?

I just want to automatically convert a KPA value to volumetric for any given KPA (0.5 increments are fine) #

**Comment by sekika** [comment]
Equation and parameters are shown, so you can easily compute any % water content of given suction by using Microsoft Excel or any programming language that you like.

Actually you can download a sample Excel file from here.
https://github.com/sekika/swrcfit/blob/master/swrc.xlsx

**Comment by TylerGriffin99** [comment]
Right, I did come across that spreadsheet. Are there any instructions on how to use it. If i simply enter the values from the swrcfit web version into the excel sheet the values are not computed. This is shown in the attached image

![image](https://user-images.githubusercontent.com/26858964/44681520-e80f5200-aa94-11e8-95fa-cba0723e9243.png)
